### ISSUE TITLE
路径不填会报错

### ISSUE THREAD

**Issue by BIGWGY** [akof1314/UnityAssetDanshari#1]
真的很好用的工具，谢谢。

有个小问题：

![图片](https://github.com/akof1314/UnityAssetDanshari/assets/13144389/a2559d9e-f933-4e0d-b6a0-5c99f9f4bec0)

![图片](https://github.com/akof1314/UnityAssetDanshari/assets/13144389/51451da0-7955-449b-a01c-f51ac5c369c3)

公共目录如果不填，会报错。

**Comment by akof1314** [comment]
已修复，并更新了其他功能
